dist: xenial
os: linux

addons:
    apt_packages:
        - lib32z1
        - lib32stdc++6

language: c

env:
  global:
    - SOURCES=$TRAVIS_BUILD_DIR/src
    - SOURCES_SM=$TRAVIS_BUILD_DIR/addons/sourcemod/scripting
    - INCLUDES=$TRAVIS_BUILD_DIR/include
    - SOURCES_RIP=$TRAVIS_BUILD_DIR/ripext
  jobs:
    - SMVERSION=1.10

install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xzf $(cat sourcemod-latest-linux)
    - git clone -b main https://github.com/ErikMinekus/sm-ripext.git $SOURCES_RIP
before_script:
    - cp -R -f $INCLUDES $SOURCES_SM
    - cp -R -f $SOURCES_RIP/pawn/scripting/include $SOURCES_SM
    - chmod +x $SOURCES_SM/spcomp
    - chmod +x $TRAVIS_BUILD_DIR/travis/compile.sh
    - chmod +x $TRAVIS_BUILD_DIR/travis/package.sh
script:
    - bash ./travis/compile.sh $SOURCES $SOURCES_SM || exit 1

before_deploy:
    - bash ./travis/package.sh $SOURCES ${TRAVIS_BUILD_NUMBER} || exit 1

deploy:
  provider: releases
  token:
    secure: LNXThCQM32MI17cNtU7bB7z4sB/hCQpaLYhzRZaCs0uFsiO+nisBM0fg5fOAg+1r02+CVWjaf/aAZthof7B7LcuKRk8zstFQgTWKUpPvVNps1nNq8A79mIAfuI/ifhtXH1WGjphHkO+8Oo/sl8uKZgx6QpOGY66HoimxbIXygbNI2Ct1L7OWzxibn8tOQPrNjrLcn8jk24sydfUIFm6U/SVNb0LENmfSl+kZONiY07QzavpbG5mCosiC6LxtuSMrc5OKYGw8gbzxCU/afwmHLQBInjmqfIhQuB2sauLIOegqcsZbUb8sikOJJ+3mZuWQ8vOt7LLhIt81F/lU8KD5wQoyZw64i3cets3k81iwWvdGpfDOL8mPIvN+T46zRR0rMrD4813+Tb5sn6uMAR0qBD2Ut51TB/XdOfKSiJJ/BwYOqZOUT2QzSJw48rNzP3Je6pkBanHyAnm+4uVdkP8fpHSR/3gi1gPiBvqgvUOKzpKZHvy2FrQ39X3fhxYiTv/qQv2A9CX38bQ7Wb/e7GG7h6c6idHWcjYGXA/FOSyxC+u2DohDWeJ+0H2IddxhqimKhA4oAyg0QhlrqxlMbPKS3sWFBJh+Uh30Pnoq6K+HWHhKlKwCBD0xNaxnA7W0ZxqQCnpiFErl0tgQfZg9lk/c9KzdIn7hYozlvCCAAptbTqQ=
  file_glob: true
  file: $SOURCES/*
  skip_cleanup: true
  on:
    tags: true
  
notifications:
    email: false
