name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.11.x' ]
        jansson-version: [ 'v-1.6.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build

      - name: Setup SourcePawn
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Checkout Jansson
        uses: actions/checkout@v3
        with:
          repository: rejchev/sm-jansson
          ref: ${{ matrix.jansson-version }}
          path: jansson
          submodules: recursive

      - name: LS
        run: |
          cd jansson
          ls -a
          
