name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.11.x' ]
        jansson-version: [ 'v-1.6.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build

      - name: Setup SourcePawn
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Checkout Jansson
        uses: actions/checkout@v3
        with:
          repository: rejchev/sm-jansson
          ref: ${{ matrix.jansson-version }}
          path: jansson
          submodules: recursive

      - name: Setup Working Directory
        run: |
          mkdir -p output/sourcemod/plugins
          cp -r -f build/src/packager/* output/sourcemod
          cp -r -f build/include  output/sourcemod/scripting 
          cp -r -f jansson/pawn/scripting/include output/sourcemod/scripting
          
      - name: Build Packager
        run: |
          spcomp build/src/packager/packager.sp -o2 -v2 -ioutput/sourcemod/scripting/include -o output/sourcemod/plugins/packager.smx

      - name: Remove Jansson Sig
        working-directory: output/sourcemod/scripting/include
        run: |
          -rm jansson.inc

      - name: Upload Packager
        uses: actions/upload-artifact@v3
        with: 
          name: upload-${{ runner.sm-version }}-${{ runner.jansson-version }}
          path: output
