name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.11.x' ]
        jansson-version: [ 'v-1.6.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: build

      - uses: actions/checkout@v3

      - name: Setup SourcePawn
        uses: rumblefrog/setup-sp@master
        with:
          version: ${{ matrix.sm-version }}

      - name: Checkout Jansson
        uses: actions/checkout@v3
        with:
          repository: rejchev/sm-jansson
          ref: ${{ matrix.jansson-version }}
          path: jansson
          submodules: recursive

      - name: Setup Working Directory
        run: |
          mkdir -p packager/sourcemod/plugins
          cp -r -f src/packager/* packager/sourcemod/
          cp -r -f include  packager/sourcemod/scripting/ 
          cp -r -f jansson/pawn/scripting/include packager/sourcemod/scripting
          
      - name: Build Packager
        run: |
          spcomp src/packager/scripting/packager.sp -O2 -v2 -ipackager/sourcemod/scripting/include -o packager/sourcemod/plugins/packager.smx

      - name: Remove Jansson Sig
        working-directory: packager/sourcemod/scripting/include
        run: |
          rm jansson.inc

      - name: Upload Packager
        uses: actions/upload-artifact@v3
        with: 
          name: packager-${{ matrix.sm-version }}
          path: packager

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sm-version: [ '1.11.x' ]

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Package artifact
        run: |
          version=`echo $GITHUB_REF | sed "s/refs\/tags\///"`
          7z a packager-${version}.${{ github.run_number }}.zip ./packager-${{ matrix.sm-version }}/*
      
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: '*.zip'
          tag: ${{ github.ref }}
          file_glob: true